export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST'
export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS'
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCESS = 'LOGIN_SUCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const persist_REHYDRATE = 'persist/REHYDRATE'

export const CADASTRO_REQUEST = 'CADASTRO_REQUEST'
export const CADASTRO_SUCESS = 'CADASTRO_SUCESS'
export const EDIT_SUCESS = 'EDIT_SUCESS'
export const CADASTRO_FAILURE = 'CADASTRO_FAILURE'